config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', sessions:'users/sessions' }
  resources :users, only: %i[show index update destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
  resources :clean_requests
  resources :cleans
  resources :locations do
    resources :cost_house_locations
    resources :plots do
      resources :plot_extras
    end
  end
  resources :houses
  resources :extras
  resources :invoices
end

app/models/invoice.rb
# frozen_string_literal: true

class Invoice < ApplicationRecord
  belongs_to :location

  def completed_cost
    # Returns the total cost of completed cleans
    @total = 0
    invoice_cleans.each do |clean|
      @location = location
      @plot = Plot.find(clean.plot_id)
      @house = House.find(@plot.house_id)
      @cost_house_location = CostHouseLocation.find_by(location: @location, house: @house)
      next unless clean.completed

      case clean.clean_type
      when 'Sparkle'
        @total += @cost_house_location.sparkle_cost
      when 'Demo'
        @total += @cost_house_location.demo_cost
      when 'Pre-Paint'
        @total += @cost_house_location.pre_paint_cost
      when 'Post-Paint'
        @total += @cost_house_location.post_paint_cost
      when 'Variation Order'
        @total += (clean.location.vo_cost * clean.hours_worked) * clean.num_people
      end

      clean.plot.plot_extras.each do |plot_extra|
        @total += plot_extra.extra.cost
      end
    end
    @total
  end

  def pending_cost
    # Returns the total cost of pending cleans
    @total = 0
    invoice_cleans.each do |clean|
      @location = location
      @plot = Plot.find(clean.plot_id)
      @house = House.find(@plot.house_id)
      @cost_house_location = CostHouseLocation.find_by(location: @location, house: @house)
      next if clean.completed

      case clean.clean_type
      when 'Sparkle'
        @total += @cost_house_location.sparkle_cost
      when 'Demo'
        @total += @cost_house_location.demo_cost
      when 'Pre-Paint'
        @total += @cost_house_location.pre_paint_cost
      when 'Post-Paint'
        @total += @cost_house_location.post_paint_cost
      end
    end
    @total
  end

  def total_cost
    # Returns the total cost of all associated cleans
    @total = completed_cost + pending_cost
    @total
  end

  def invoice_cleans
    # Returns an ActiveModel collection of cleans that are within the start and end dates of the invoice
    @site_cleans = Clean.where(location_id: location_id)
    @site_start_date_cleans = @site_cleans.where('date >= ?', start_date)
    @site_month_cleans = @site_start_date_cleans.where('date <= ?', end_date)

    @site_month_cleans
  end
end

app/controllers/invoices_controller.rb
# frozen_string_literal: true

class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[show edit update destroy]
  load_and_authorize_resource

  def new
    @invoice = Invoice.new
  end

  def create
    @invoice = Invoice.new(invoice_params)
    if @invoice.save
      flash[:notice] = 'invoice created'
      redirect_to @invoice
    else
      render 'new'
    end
  end

  def index
    @invoices = Invoice.all
  end

  def show
    @cleans = Clean.where({ date: @invoice.start_date..@invoice.end_date, completed: true })
  end

  def destroy
    @invoice.destroy
    flash[:notice] = 'Invoice Deleted'
    redirect_to invoices_path
  end

  private

  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  def invoice_params
    params.require(:invoice).permit(:start_date, :end_date, :location_id)
  end
end

app/helpers/invoices_helper.rb
# frozen_string_literal: true

module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: @invoice, local: true) do |f| %>

  <div class="form-group row">
    <%= f.label :location, class:"col-form-label col-2" %>
    <%= f.collection_select :location_id, Location.all, :id, :site_name %>
  </div>

  <div class="form-group row">
    <%= f.label :start_date, class:"col-form-label col-2" %>
    <%= f.date_field :start_date, class:"form-control col-10"  %>
  </div>

  <div class="form-group row">
    <%= f.label :end_date, class:"col-form-label col-2" %>
    <%= f.date_field :end_date, class:"form-control col-10"  %>
  </div>

  <div class="form-group row justify-content-center">
    <%= f.submit class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/invoices/index.html.erb
<h1>Invoices</h1>
<% Location.all.each do |location| %>
  <h3><%=location.site_name%></h3>
  <hr />
  <% location.invoices.each do |invoice| %>
    <%= link_to invoice.start_date.strftime('%d %b %Y') + ' - ' + invoice.end_date.strftime('%d %b %Y'), invoice_path(invoice)%> <br />
  <% end %>
  <hr />
<% end %>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form'%>

app/views/invoices/show.html.erb
Start Date: <%= @invoice.start_date.strftime("%d/%^b/%Y") %> <br />
End Date: <%= @invoice.end_date.strftime("%d/%^b/%Y") %> <br />
Location: <%= @invoice.location.site_name %>
<table class='table table-striped table-hover'>
  <thead>
    <th scope="col">Clean No*</th>
    <th scope="col">Date</th>
    <th scope="col">Plot No*</th>
    <th scope="col">Clean Type </th>
    <th scope="col">Cost </th>
    <th scope="col">Extras </th>
  </thead>
  <% @cleans.each do |clean| %>
    <tr>
      <td><%= link_to clean.id, clean_path(clean) %> </td>
      <td><%= clean.date.strftime("%d/%m/%Y")%> </td>
      <td><%= Plot.find(clean.plot_id).number %> </td>
      <td><%= clean.clean_type %></td>
      <td>£<%= clean.clean_cost %></td>
      <td><%= clean.extras_total > 0 ? "£" + clean.extras_total.to_s : "N/A" %><td>
    </tr>
  <% end %>
</table>

Total Cost: £<%= @invoice.completed_cost%> <br />

Number of cleans: <%= @invoice.invoice_cleans.count %>