config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', sessions:'users/sessions' }
  resources :users, only: %i[show index update destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
  resources :clean_requests
  resources :cleans
  resources :locations do
    resources :cost_house_locations
    resources :plots do
      resources :plot_extras
    end
  end
  resources :houses
  resources :extras
  resources :invoices
end

app/controllers/houses_controller.rb
# frozen_string_literal: true

class HousesController < ApplicationController
  before_action :set_house, only: %i[show edit update destroy]
  load_and_authorize_resource
  def new
    @house = House.new
  end

  def create
    @house = House.new(house_params)
    if @house.save
      flash[:notice] = 'House created'
      redirect_to @house
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @house.update(house_params)
      flash[:notice] = 'House updated'
      redirect_to @house
    else
      render 'edit'
    end
  end

  def index
    @houses = House.all
  end

  private

  def set_house
    @house = House.find(params[:id])
  end

  def house_params
    params.require(:house).permit(:sales_name, :build_number, :bedrooms)
  end
end

app/helpers/houses_helper.rb
# frozen_string_literal: true

module HousesHelper
end

app/views/houses/_form.html.erb
<div>
    <%= form_with(model: [@house], local: true) do |f| %>
        
        <div class="form-group row">
            <%= f.label :sales_name, class:"col-form-label col-2" %>
            <%= f.text_field :sales_name, class:"form-control col-10"  %>
        </div>

        <div class="form-group row">
            <%= f.label :build_number, class:"col-form-label col-2" %>
            <%= f.text_field :build_number, class:"form-control col-10"  %>
        </div>

        <div class="form-group row">
            <%= f.label :bedrooms, "Number of Bedrooms", class:"col-form-label col-2" %>
            <%= f.text_field :bedrooms, class:"form-control col-10"  %>
        </div>

        <div class="form-group row justify-content-center">
        <%= f.submit class:"btn btn-lg btn-primary" %>
        </div>

    <% end %>
</div>

app/views/houses/edit.html.erb
<h1>Editing House</h1>
<%= render 'form'%>

app/views/houses/index.html.erb
<h1>House Index</h1>
<ul class="list-group">
    <% @houses.each do |house| %>
        <li class="list-group-item list-group-item-action">
            <%= link_to house.sales_name, house_path(house) %>
        </li>
    <% end %>
</ul>

<div>
    <%= link_to 'New House', new_house_path %>
</div>

app/views/houses/new.html.erb
<h1>New House</h1>
<%= render 'form' %>

app/views/houses/show.html.erb
<h1><%= @house.sales_name %></h1>
<p>Build number:<%= @house.build_number %></p>
<p>Number of bedrooms: <%= @house.bedrooms if @house.bedrooms %> </p>

<div><%= link_to 'Edit', edit_house_path(@house) %> </div>