config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', sessions:'users/sessions' }
  resources :users, only: %i[show index update destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
  resources :clean_requests
  resources :cleans
  resources :locations do
    resources :cost_house_locations
    resources :plots do
      resources :plot_extras
    end
  end
  resources :houses
  resources :extras
  resources :invoices
end

app/models/clean_request.rb
# frozen_string_literal: true

class CleanRequest < ApplicationRecord
  include ActiveModel::Dirty

  define_attribute_method :approved

  validate :date_24_hours_in_advance

  belongs_to :user
  belongs_to :location
  has_one :clean

  after_update :approved_check

  def date_24_hours_in_advance
    @today = Date.today
    errors.add :base, 'Date must be at least a day in advance' unless (@today + 1) <= date
  end

  def approved_check
    if changed_attributes.has_key?(:approved)
      UserMailer.with(clean_request: self, user: user).clean_request_approval_change_email.deliver_now if approved
    else
      false
    end
  end

  def convert_to_clean
    @clean = Clean.create(
      date: date,
      location_id: location_id,
      plot_id: location.plots.find_by(number: plot_number).id,
      clean_type: clean_type,
      completed: false
    )
  end
end

app/controllers/clean_requests_controller.rb
# frozen_string_literal: true

class CleanRequestsController < ApplicationController
  before_action :set_clean_request, except: %i[index new create convert]
  load_and_authorize_resource

  def new
    @clean_request = CleanRequest.new
  end

  def create
    @clean_request = CleanRequest.new(clean_request_params)
    @clean_request.user_id = current_user.id

    if @clean_request.save!
      flash[:notice] = 'Clean request was succesfully created!'
      redirect_to @clean_request
      UserMailer.with(user: current_user, clean_request: @clean_request).new_clean_request_email.deliver_now
    else
      render 'new'
    end
  end

  def show; end

  def index
    @clean_requests = CleanRequest.all
  end

  def update
    if @clean_request.update(clean_request_params)
      flash[:notice] = 'Clean Request successfully updated!'
      redirect_to @clean_request
    else
      render 'edit'
    end
  end

  def edit; end

  def destroy
    @clean_request.destroy
    flash[:notice] = 'Clean request removed'
    redirect_to clean_requests_path
  end

  private

  def set_clean_request
    @clean_request = CleanRequest.find(params[:id])
  end

  def clean_request_params
    params.require(:clean_request).permit(:clean_type, :location_id, :notes, :approved, :date, :plot_number,
                                          :clean)
  end
end

app/helpers/clean_requests_helper.rb
# frozen_string_literal: true

module CleanRequestsHelper
end

app/views/clean_requests/_form.html.erb
<div class>
  <%= form_with(model: @clean_request, local: true) do |f| %>

    <div class="form-group row">
      <%= f.label "Location: ", class:"col-form-label col-2"%>
      <%= f.collection_select :location_id, Location.all, :id, :site_name, {}, {class: "form-control col-10"} %>
    </div>
    
    <div class="form-group row">
      <%= f.label :plot_number, class:"col-form-label col-2" %>
      <%= f.text_field :plot_number, class:"form-control col-10"  %>
    </div>

    <div class="form-group row">
      <%= f.label :date, class:"col-form-label col-2"  %>
      <%= f.date_field :date, class:"form-control col-10"%>
    </div>

    <div class="form-group row">
      <%= f.label :clean_type, 'Type of Clean', class:"col-form-label col-2"  %>
      <%= f.select(:clean_type, options_for_select(["Build", "Sparkle", "Demo"]), {},  {class:"form-control col-10"}) %>
    </div>

    <div class="form-group row">
      <%= f.label :notes, class:"col-form-label col-2"  %>
      <%= f.text_area :notes, class:"form-control col-10" %>
    </div>
  	<% if current_user.admin? %>
      <div class="form-group row">
        <%= f.label :approved, class:"col-form-label col-2"  %>
        <%= f.check_box :approved, class:"form-control col-10" %>
      </div>
    <% end %>
    <div class="form-group row justify-content-center">
      <%= f.submit class:"btn btn-lg btn-primary" %>
    </div>

  <% end %>
</div>

app/views/clean_requests/index.html.erb
<table class='table table-striped table-hover'>
  <thead>
    <th scope="col">Request No*</th>
    <th scope="col">Date(s) Requested</th>
    <th scope="col">Request sent on </th>
    <th scope="col">Approved </th>
  </thead>
  <% @clean_requests.each do |clean_request| %>
    <% if can? :read, clean_request%>
      <tr scope="row">
        <td><%= link_to clean_request.id, clean_request %></td>
        <td><%= clean_request.date.strftime('%d/%m/%Y') %></td>
        <td><%= clean_request.created_at.strftime('%d/%m/%Y') %></td>
        <td><%= clean_request.approved? ? 'Y' : 'N' %></td>
      </tr>
    <% end %>
  <% end %> 
</table>

<div>
  <%= link_to 'New Request', new_clean_request_path %>
</div>

app/views/clean_requests/new.html.erb
<h1>New Clean Request </h1>
<%= render 'form', clean_request:@clean_request %>

app/views/clean_requests/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">Clean Request</h1>
    <div> Date Requested:<%= @clean_request.date%> </div>
    <div> Location: <%= @clean_request.location.site_name  if @clean_request.location %> </div>
    <div> Plot Number: <%= @clean_request.plot_number %> </div>
    <div> Clean requested: <%= @clean_request.clean_type %> </div>
    <div> Notes:<%= @clean_request.notes%> </div>
    <div> Requested by: <%= User.find(@clean_request.user_id).email %></div>
    <div><%= link_to 'Edit', edit_clean_request_path(@clean_request) %></div>
    <div><%= link_to 'Delete request', @clean_request, method:(:delete), data: { confirm: "Are you sure?"} %></div>
</div>

<% if current_user.admin? %>
  <div>
    <h3>Admin</h3>
    <% if !@clean_request.approved %>
      <%= form_with(model: @clean_request, local: true) do |f| %>
          <div class="form-group row">
            <%= f.label :approved, class:"col-form-label col-2"  %>
          <%= f.check_box :approved, class:"form-control col-10" %>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit class:"btn btn-lg btn-primary" %>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>