config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', sessions:'users/sessions' }
  resources :users, only: %i[show index update destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
  resources :clean_requests
  resources :cleans
  resources :locations do
    resources :cost_house_locations
    resources :plots do
      resources :plot_extras
    end
  end
  resources :houses
  resources :extras
  resources :invoices
end

app/models/extra.rb
# frozen_string_literal: true

class Extra < ApplicationRecord
  has_many :plot_extras
  has_many :plots, through: :plot_extras
end

app/controllers/extras_controller.rb
# frozen_string_literal: true

class ExtrasController < ApplicationController
  before_action :set_extra, only: %i[show edit update destroy]
  load_and_authorize_resource
  def new
    @extra = Extra.new
  end

  def create
    @extra = Extra.new(extra_params)
    if @extra.save
      flash[:notice] = 'Extra created'
      redirect_to @extra
    else
      render 'new'
    end
  end

  def show; end

  def index
    @extras = Extra.all
  end

  def edit; end

  def update
    if @extra.update(extra_params)
      flash[:notice] = 'Extra updated'
      redirect_to @extra
    else
      render 'edit'
    end
  end

  def destroy; end

  private

  def set_extra
    @extra = Extra.find(params[:id])
  end

  def extra_params
    params.require(:extra).permit(:name, :cost)
  end
end

app/helpers/extras_helper.rb
# frozen_string_literal: true

module ExtrasHelper
end

app/views/extras/_form.html.erb
<%= form_with(model: @extra, local: true) do |f| %>

  <div class="form-group row">
    <%= f.label :name, class:"col-form-label col-2"%>
    <%= f.text_field :name, class:"form-control col-10" %>
  </div>

  <div class="form-group row">
      <%= f.label :cost, class:"col-form-label col-2"%>
      <%= f.text_field :cost, class:"form-control col-10" %>
  </div>

  <div class="form-group row justify-content-center">
    <%= f.submit class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/extras/edit.html.erb
<h1>Extras#edit</h1>
<%= render 'form' %>

app/views/extras/index.html.erb
<h1>Extras#index</h1>
<% @extras.each do |extra| %> 
  <%= link_to extra.name, extra %> £<%= extra.cost%>
<% end %>
<hr />
<%= link_to 'New Extra', new_extra_path %>

app/views/extras/new.html.erb
<h1>Extras#new</h1>
<%= render 'form'%>

app/views/extras/show.html.erb
<h1><%=@extra.name%></h1>
<p>Cost: £<%= @extra.cost%></p>
<%= link_to 'Edit', edit_extra_path(@extra) %>